/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesgraficas;

import datechooser.beans.DateChooserCombo;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import liquidacion.AltaOrden;
import liquidacion.Filtro;
import liquidacion.Mensaje;
import liquidacion.MensajeDao;
import liquidacion.Orden;
import liquidacion.OrdenDao;
import utiles.Utiles;

/**
 *
 * @author alejandro.delmedico
 */
public class InterfazConsultaOrdenes extends javax.swing.JFrame {

    private ArrayList<Orden> ordenes;

    /**
     * Creates new form InterfazConsulta
     */
    public InterfazConsultaOrdenes() {
        initComponents();
        listarConsultasOrden();
        liberarButton.setEnabled(false);
        liquidarButton.setEnabled(false);
        consultaButton.setEnabled(false);
        editButton.setEnabled(false);
        responderButton.setEnabled(false);
    }

    public Filtro recogerFiltros() {
        Filtro filtro = new Filtro();
        filtro.setBICEntidad(entidadTF.getText());
        filtro.setRefOrden(refOrdenTF.getText());
        filtro.setEstado(Utiles.setDataFrom(estadoCB));
        filtro.setCorresponsalPropio(corresponsalTF.getText());
        filtro.setSentido(Utiles.setDataFrom(sentidoCB));
        filtro.setDivisa(Utiles.setDataFrom(divisaCB));

        filtro.setImporte(Utiles.setDoubleFrom(importeDesdeTF));
        filtro.setImporteMax(Utiles.setDoubleFrom(importeHastaTF));

        filtro.setFechaValor(Utiles.setDateFrom(valorDesdeDC));
        filtro.setFechaValorMax(Utiles.setDateFrom(valorHastaDC));
        filtro.setFechaLiberacion(Utiles.setDateFrom(liberacionDesdeDC));
        filtro.setFechaLiberacionMax(Utiles.setDateFrom(liberacionHastaDC));
        filtro.setFechaLiquidacion(Utiles.setDateFrom(liquidacionDesdeDC));
        filtro.setFechaLiquidacionMax(Utiles.setDateFrom(liquidacionHastaDC));

        return filtro;
    }

    public void listarConsultasOrden() {
        OrdenDao dao = new OrdenDao();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"Tipo orden", "Ref. orden", "Contrapartida", "Sentido",
            "Importe", "Divisa", "Fecha entrada", "Fecha valor", "Fecha liquidación", "Fecha liberacion",
            "Estado", "TRN", "Corresponsal propio", "Cuenta corresponsal propio"});

        ordenes = dao.listarOrdenes(recogerFiltros());
        jTable1.setModel(dtm);

        for (Orden o : ordenes) {
            Object[] ob = new Object[14];
            ob[0] = o.getTipoMensaje(); //Tipo orden
            ob[1] = o.getRefOrden();
            ob[2] = o.getContrapartida();
            ob[3] = o.getSentido();
            ob[4] = o.getImporte();
            ob[5] = o.getDivisa();
            ob[6] = new SimpleDateFormat("ddMMMyyyy").format(o.getFechaEntrada());
            ob[7] = new SimpleDateFormat("ddMMMyyyy").format(o.getFechaValor());
            try {
                ob[8] = new SimpleDateFormat("ddMMMyyyy").format(o.getFechaLiquidacion());
            } catch (Exception e) {
                ob[8] = "";
            }
            try {
                ob[9] = new SimpleDateFormat("ddMMMyyyy").format(o.getFechaLiberacion());
            } catch (Exception e) {
                ob[9] = "";
            }
            ob[10] = o.getEstado();
            ob[11] = o.getUltimoTRN();
            ob[12] = o.getCorresponsalPropio();
            ob[13] = o.getCuentaCorresponsalPropio();
            dtm.addRow(ob);
        }
        dao.closeConnetion();
        
        liberarButton.setEnabled(false);
        liquidarButton.setEnabled(false);
        consultaButton.setEnabled(false);
        editButton.setEnabled(false);
        responderButton.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        entidadTF = new javax.swing.JTextField();
        refOrdenTF = new javax.swing.JTextField();
        corresponsalTF = new javax.swing.JTextField();
        divisaCB = new javax.swing.JComboBox<>();
        importeDesdeTF = new javax.swing.JTextField();
        importeHastaTF = new javax.swing.JTextField();
        sentidoCB = new javax.swing.JComboBox<>();
        estadoCB = new javax.swing.JComboBox<>();
        liberarButton = new javax.swing.JButton();
        liquidarButton = new javax.swing.JButton();
        consultaButton = new javax.swing.JButton();
        altaOrdenButton = new javax.swing.JButton();
        liberacionHastaDC = new datechooser.beans.DateChooserCombo();
        liberacionDesdeDC = new datechooser.beans.DateChooserCombo();
        valorDesdeDC = new datechooser.beans.DateChooserCombo();
        liquidacionDesdeDC = new datechooser.beans.DateChooserCombo();
        valorHastaDC = new datechooser.beans.DateChooserCombo();
        liquidacionHastaDC = new datechooser.beans.DateChooserCombo();
        searchButton = new javax.swing.JButton();
        quitarFiltrosButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        responderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta de ordenes");

        jLabel2.setText("BIC Entidad");

        jLabel3.setText("Estado de la orden");

        jLabel4.setText("Sentido");

        jLabel5.setText("Importe desde");

        jLabel6.setText("F. liberación desde");

        jLabel7.setText("F. valor desde");

        jLabel8.setText("F. liquidación desde");

        jLabel9.setText("Ref. orden");

        jLabel10.setText("Corresponsal propio");

        jLabel11.setText("Divisa");

        jLabel12.setText("Importe hasta");

        jLabel13.setText("F. liberación hasta");

        jLabel14.setText("F. valor hasta");

        jLabel15.setText("F. liquidación hasta");

        entidadTF.setEditable(false);
        entidadTF.setText("BSCHESMMXXX");

        divisaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "EUR", "GBP", "USD", "CAD", "AUS", "JPY", "CHF", "SEK", "HKD", "NOK" }));

        sentidoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Cobro", "Pago" }));

        estadoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "No liberada", "Liberada", "ACK", "Incidencia", "Liquidada" }));

        liberarButton.setText("Liberar");
        liberarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberarButtonActionPerformed(evt);
            }
        });

        liquidarButton.setText("Liquidar manual");
        liquidarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liquidarButtonActionPerformed(evt);
            }
        });

        consultaButton.setText("Consultar mensajes");
        consultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaButtonActionPerformed(evt);
            }
        });

        altaOrdenButton.setText("Dar de alta orden");
        altaOrdenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaOrdenButtonActionPerformed(evt);
            }
        });

        liberacionHastaDC.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                    new java.awt.Color(187, 187, 187),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    try {
        liberacionHastaDC.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    liberacionDesdeDC.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
try {
    liberacionDesdeDC.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    valorDesdeDC.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
try {
    valorDesdeDC.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    liquidacionDesdeDC.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
try {
    liquidacionDesdeDC.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    valorHastaDC.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
try {
    valorHastaDC.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    liquidacionHastaDC.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 18),
                new java.awt.Color(187, 187, 187),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
try {
    liquidacionHastaDC.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    searchButton.setText("Aplicar filtros");
    searchButton.setMaximumSize(new java.awt.Dimension(144, 32));
    searchButton.setMinimumSize(new java.awt.Dimension(144, 32));
    searchButton.setPreferredSize(new java.awt.Dimension(144, 32));
    searchButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchButtonActionPerformed(evt);
        }
    });

    quitarFiltrosButton.setText("Quitar filtros");
    quitarFiltrosButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            quitarFiltrosButtonActionPerformed(evt);
        }
    });

    editButton.setText("Editar incidencia");
    editButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            editButtonActionPerformed(evt);
        }
    });

    responderButton.setText("Responder mensaje");
    responderButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            responderButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1255, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(liquidacionDesdeDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorDesdeDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estadoCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sentidoCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importeDesdeTF)
                        .addComponent(liberacionDesdeDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entidadTF))
                    .addGap(75, 75, 75)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel14)
                        .addComponent(jLabel13)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9))
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(corresponsalTF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(divisaCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(importeHastaTF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(liberacionHastaDC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorHastaDC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(liquidacionHastaDC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refOrdenTF))
                    .addGap(100, 100, 100)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addComponent(quitarFiltrosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(responderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(altaOrdenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addComponent(consultaButton, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addComponent(liquidarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addComponent(liberarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jLabel1)
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel2)
                .addComponent(entidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9)
                .addComponent(refOrdenTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(liberarButton))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel3)
                .addComponent(estadoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10)
                .addComponent(corresponsalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(quitarFiltrosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(liquidarButton))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel4)
                .addComponent(sentidoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11)
                .addComponent(divisaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(consultaButton))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel5)
                .addComponent(importeDesdeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel12)
                .addComponent(importeHastaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel6)
                .addComponent(liberacionDesdeDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel13)
                .addComponent(liberacionHastaDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel7)
                .addComponent(valorDesdeDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel14)
                .addComponent(valorHastaDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(altaOrdenButton))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel8)
                .addComponent(liquidacionDesdeDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel15)
                .addComponent(liquidacionHastaDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(responderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaOrdenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaOrdenButtonActionPerformed
        // TODO add your handling code here:
        AltaOrden altaOrden = new AltaOrden();
        altaOrden.setLocationRelativeTo(this);
        altaOrden.setVisible(true);

        altaOrden.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                listarConsultasOrden();
            }
        });
    }//GEN-LAST:event_altaOrdenButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        listarConsultasOrden();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void quitarFiltrosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarFiltrosButtonActionPerformed
        // TODO add your handling code here:
        entidadTF.setText("");
        refOrdenTF.setText("");
        estadoCB.setSelectedIndex(0);
        corresponsalTF.setText("");
        sentidoCB.setSelectedIndex(0);
        divisaCB.setSelectedIndex(0);
        importeDesdeTF.setText("");
        importeHastaTF.setText("");

        valorDesdeDC.setCurrent(null);
        valorHastaDC.setCurrent(null);
        liberacionDesdeDC.setCurrent(null);
        liberacionHastaDC.setCurrent(null);
        liquidacionDesdeDC.setCurrent(null);
        liquidacionHastaDC.setCurrent(null);
    }//GEN-LAST:event_quitarFiltrosButtonActionPerformed

    private void liquidarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liquidarButtonActionPerformed
        // TODO add your handling code here:
        try {
            int row = jTable1.getSelectedRow();
            Orden orden = ordenes.get(row);
            if (!orden.getEstado().equals("Liquidada")) {
                int selected = JOptionPane.showConfirmDialog(this, "Liquidar orden", "Liquidar", JOptionPane.YES_NO_OPTION);
                if (selected == 0) {
                    OrdenDao dao = new OrdenDao();
                    dao.liquidarManualOrden(orden);
                    JOptionPane.showMessageDialog(this, "Orden liquidada correctamente");
                }
            } else {
                JOptionPane.showMessageDialog(this, "La orden seleccionada ya ha sido liquidada");
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        } finally {
            listarConsultasOrden();
        }
    }//GEN-LAST:event_liquidarButtonActionPerformed

    private void consultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaButtonActionPerformed
        try {
            int row = jTable1.getSelectedRow();
            Orden orden = ordenes.get(row);
            InterfazConsultaMensajes consultaMensaje = new InterfazConsultaMensajes(orden);
            consultaMensaje.setLocationRelativeTo(this);
            consultaMensaje.setVisible(true);

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden");
        }
    }//GEN-LAST:event_consultaButtonActionPerformed

    private void liberarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberarButtonActionPerformed
        try {
            int row = jTable1.getSelectedRow();
            Orden orden = ordenes.get(row);
            if (orden.getEstado().equals("No Liberado") || orden.getEstado().equals("Incidencia")) {
                OrdenDao dao = new OrdenDao();
                dao.liberarOrden(orden);
                if(orden.getSentido().equals("Pago")){
                    MensajeDao mensajeDao = new MensajeDao();
                    String TRN = mensajeDao.generarTrn(orden);
                    Mensaje mensaje = new Mensaje(orden,TRN);
                    mensaje.setTipoMensaje(orden.getTipoMensaje());
                    mensajeDao.añadir(mensaje);                    
                } 
                JOptionPane.showMessageDialog(this, "Orden liberada correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "La orden ya se ha liberado");
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden");
        } finally {
            listarConsultasOrden();
        }
    }//GEN-LAST:event_liberarButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        try {
            int row = jTable1.getSelectedRow();
            Orden orden = ordenes.get(row);
            AltaOrden altaOrden = new AltaOrden(orden);
            altaOrden.setLocationRelativeTo(this);
            altaOrden.setVisible(true);
            
            altaOrden.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                listarConsultasOrden();
            }
            });

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden");
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void responderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responderButtonActionPerformed
        try {
            int row = jTable1.getSelectedRow();
            Orden orden = ordenes.get(row);
            String estado = orden.getEstado();
            String swift = "MT";
            
            OrdenDao ordenDao = new OrdenDao();
            MensajeDao mensajeDao = new MensajeDao();
            String TRN = mensajeDao.generarTrn(orden);
            Mensaje mensaje = new Mensaje();
            mensaje.setOrden(orden);
            mensaje.setTRN(TRN);
            if(orden.getSentido().equals("Pago")){
                if(estado.equals("Liberada")){
                    String selecciones[] = {"ACK","NACK"};
                    swift = (String)JOptionPane.showInputDialog(this, "Seleccione tipo de mensaje", "Responder mensaje"
                            , JOptionPane.QUESTION_MESSAGE, null, selecciones, selecciones[0]);
                    mensaje.setTipoMensaje(swift);
                    if(swift.equals("NACK"))
                        swift = "Incidencia";
                    ordenDao.actualizarEstado(orden, swift);
                } else if(estado.equals("ACK")){
                    mensaje.setTipoMensaje("MT900");
                }
            }else{
                mensaje.setTipoMensaje("MT910");
            }
            mensaje.setTRNrecibido(ordenDao.getPrimerTRN(orden.getId()));
            mensaje.setSwift(mensaje.responderSwift());
            mensajeDao.añadir(mensaje);
            if(swift.equals("MT")){
                ordenDao.liquidarOrden(orden);
                JOptionPane.showMessageDialog(this, "Orden liquidada correctamente");
            }                
        
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden");
        } finally {
            listarConsultasOrden();
        }
    }//GEN-LAST:event_responderButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        liberarButton.setEnabled(false);
        liquidarButton.setEnabled(false);
        consultaButton.setEnabled(true);
        editButton.setEnabled(false);
        responderButton.setEnabled(false);
        evaluarEstado();
    }//GEN-LAST:event_jTable1MouseClicked

    public void evaluarEstado(){
        int row = jTable1.getSelectedRow();
        Orden orden = ordenes.get(row);
        String estado = orden.getEstado();

        if(estado.equals("No Liberado")){
            liberarButton.setEnabled(true);
            liquidarButton.setEnabled(true);
        }
        if(estado.equals("Liberada") || estado.equals("ACK")){
            liquidarButton.setEnabled(true);
            responderButton.setEnabled(true);
        }
        if(estado.equals("Incidencia")){
            liquidarButton.setEnabled(true);
            editButton.setEnabled(true);
        }   
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultaOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConsultaOrdenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaOrdenButton;
    private javax.swing.JButton consultaButton;
    private javax.swing.JTextField corresponsalTF;
    private javax.swing.JComboBox<String> divisaCB;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField entidadTF;
    private javax.swing.JComboBox<String> estadoCB;
    private javax.swing.JTextField importeDesdeTF;
    private javax.swing.JTextField importeHastaTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private datechooser.beans.DateChooserCombo liberacionDesdeDC;
    private datechooser.beans.DateChooserCombo liberacionHastaDC;
    private javax.swing.JButton liberarButton;
    private datechooser.beans.DateChooserCombo liquidacionDesdeDC;
    private datechooser.beans.DateChooserCombo liquidacionHastaDC;
    private javax.swing.JButton liquidarButton;
    private javax.swing.JButton quitarFiltrosButton;
    private javax.swing.JTextField refOrdenTF;
    private javax.swing.JButton responderButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> sentidoCB;
    private datechooser.beans.DateChooserCombo valorDesdeDC;
    private datechooser.beans.DateChooserCombo valorHastaDC;
    // End of variables declaration//GEN-END:variables
}
